### ISSUE TITLE
Face and mask alignment 

### ISSUE THREAD

**Issue by AmiraAlsamawi** [liangchen527/SLADD#10]
@liangchen527 
Mr. Liang Chen, would you please tell us if you extracted and aligned the faces and masks as a preprocessing step for the data? I tried training the model using the original FF++ dataset, but I faced the error ('Face detetor failed ...') for most of the frames. 

If you preprocessed the frames to crop and align faces and masks, I would really appreciate it if you would share the code or give us more details on how to do so. I tried dlib for faces, but I could not do the same for the masks.

Thank you in advance.

**Comment by githuboflk** [comment]
I got this problem.

**Comment by liangchen527** [comment]
Happy to help. Please email me directly for the preprocess codes.

**Comment by bestalllen** [comment]
Hello, Mr. Chen, i have the same problem about extracting masks, could you share preprocess codes for me? My email address is 1252832845@qq.com. I would appreciate your help~

**Comment by Pudge-tao** [comment]
i got same problem,could u share the codes for me. 1257907723@qq.com,thanks a lot

**Comment by EifelTing** [comment]
I got the same problem, could you share the preprocess codes for me. coderdyf@163.com,thank you very much

**Comment by allprover** [comment]
I got the same problem, could you share the preprocess codes for me.1322712308@qq.com,thanks
