### ISSUE TITLE
In "load_image"  Function of FFdata.py,  how can load mask image?

### ISSUE THREAD

**Issue by chenjunlinlin** [liangchen527/SLADD#14]
------------------------------------------------------------------
    def load_image(self, name, idx):
        impath = '{}/{}/{:04d}.png'.format(self.data_root, name, int(idx))
        ########
        maskpath = '{}/{}/{:04d}_mask.png'.format(self.mask_root, name, int(idx))
        mask = load_mask(maskpath, size=self.res)
        ########
        img = load_rgb(impath, size=self.res)
------------------------------------------------------------------

I want to know why the name of both image and mask is Same. if label is 0, the name is real/xxx_xxx. so how can read mask? because the mask_path is mask/real/xxx_xxx. I can't find it in data folder.

**Comment by chenjunlinlin** [comment]
> ```
> def load_image(self, name, idx):
>     impath = '{}/{}/{:04d}.png'.format(self.data_root, name, int(idx))
>     ########
>     maskpath = '{}/{}/{:04d}_mask.png'.format(self.mask_root, name, int(idx))
>     mask = load_mask(maskpath, size=self.res)
>     ########
>     img = load_rgb(impath, size=self.res)
> ```
> 
> I want to know why the name of both image and mask is Same. if label is 0, the name is real/xxx_xxx. so how can read mask? because the mask_path is mask/real/xxx_xxx. I can't find it in data folder.

**Comment by Arg-Li** [comment]
Have you solved it？
