### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by YYY-12138** [liangchen527/SLADD#2]
May I ask when the code can be released? I have a class assignment related to this and I'd like to refer to your excellent work. Thank you

**Comment by YYY-12138** [comment]
If it is not convenient to make it public, could you send it to me privately?
My email is 2212238408@qq.com which is used frequently.

**Comment by liangchen527** [comment]
Thanks for your interest, code is released.

**Comment by YYY-12138** [comment]
Dear Liang Chen,


Congratulation​s to&nbsp;your brilliant achievement and&nbsp;thanks again for your detailed code as well as readme file released in the github.&nbsp;


I'm Yang Jiacheng from Tongji University, and during this shcool year I'm also doing some work in this area due to a class tutored by Phd. Fu Changhong.


Due to my&nbsp;Low-grade equipment, I can hardly make the train code run or even successfully implement it.




I would appreciate it if you could send the trained model file(eg. pth file) to me, and I swear not to use this model anywhere else.

Thanks for your previous reply, and I'm looking forward to keeping in touch with you in the future for further study in academic or other fields.


Best wishes,
Yang Jiacheng













------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liangchen527/SLADD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月29日(星期天) 下午4:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liangchen527/SLADD] Code Release (Issue #2)





 
Closed #2 as completed.
