### ISSUE TITLE
What is the recommended number of frames when training on ResNet18  

### ISSUE THREAD

**Issue by AmiraAlsamawi** [liangchen527/SLADD#8]
@liangchen527 
I am facing a shortage of resources and will train the ResNet18 model instead of Xception. What is your recommendation for the minimum number of frames (samples) per video for the training set? The original work used 270 frames/video on the Xception model, but I want to minimize this number as much as possible.

**Comment by liangchen527** [comment]
Sorry, I didn't try other options. Guess the more frames the better?
